### PR TITLE
fix(minio): add support for minio

### LINKED ISSUE #25: Use minio as the default storage backend
Currently registry uses emptydir(filesystem) as the default storage.Instead use minio as the default storage.

### PR DESCRIPTION
**Pull request by kmala**
Add support for minio as the storage backend.
Fixes #25

### CODE REVIEW

**Comment by bacongobbler** [comment]
I notice that there's no flag to set the signature version to v4 which is [a requirement for minio](https://github.com/minio/minio#how-to-use-aws-cli-with-minio). Is that flag missing here?

**Comment by kmala** [comment]
we are using the aws-sdk-go which uses signature version v4 by default.

**Comment by bacongobbler** [comment]
Interesting. Most clients use sigv2 by default. That's one less problem.

**Comment by bacongobbler** [comment]
is this reliant on https://github.com/deis/distribution/pull/2?

**Comment by kmala** [comment]
yes

**Comment by arschles** [comment]
@kmala Does registry support GCS? https://github.com/deis/registry/pull/27/files#diff-7ddfb3e035b42cd70649cc33393fe32cR21 seems to indicate so. If so, and this repo uses aws-sdk-go, it won't work with GCS. GCS requires signature version 2 and aws-sdk-go only has support for v4 :(

If it helps, I've used [minio-go](https://github.com/minio/minio-go) in deis/builder#223 to accommodate GCS in addition to S3/Minio.

**Comment by kmala** [comment]
@arschles there are different driver classes to connect different backend in the docker distribution. To connect to GCS it uses the gcloud go package.
https://github.com/docker/distribution/tree/master/registry/storage/driver

**Comment by arschles** [comment]
@kmala - cool! I had commented at https://github.com/deis/distribution/pull/2/files#r54913818 that the code won't work with GCS, but you can probably ignore that since I guess it's not designed to :)

**Comment by arschles** [comment]
@kmala the code LGTM. Has this been manually tested in a Deis cluster against Minio?

**Comment by kmala** [comment]
yes....and it requires https://github.com/deis/charts/pull/131

**Comment by arschles** [comment]
@kmala ok, looks like this is good to merge then

**Pull request merged**
