### PR TITLE
fix(storage): make changes to support the object storage secret

### PR DESCRIPTION
**Pull request by kmala**
make changes to support the object storage secret(https://github.com/deis/charts/pull/171)

### CODE REVIEW

**Comment by smothiki** [comment]
Do we have similar changes reflected in Builder and Database

**Comment by kmala** [comment]
yes.

**Comment by arschles** [comment]
@kmala code LGTM here. Can you submit a PR to `deis/charts` that  I think it would be helpful if you could submit a PR to `deis/charts` that only contains the changes needed for registry? I'm requesting this so that you can merge just that PR and this simultaneously. Once you do, let me know and I'll review that and LGTM this

**Comment by kmala** [comment]
https://github.com/deis/charts/pull/171

**Comment by arschles** [comment]
After discussing the impact of https://github.com/deis/charts/pull/171, I now understand that PR isn't breaking. I'm LGTMing this PR, conditional on merging deis/charts#171

**Pull request merged**
